version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/tailwind/Dockerfile
    command: /start_tailwind
    image: django_tailwind_app_local:latest
    container_name: django_tailwind_app
    # depends_on:
    #   - rabbitmq
    env_file:
      - ./.envs/.local/.django
    volumes:
      - .:/app_local
      - static_tailwind_v:/app_local/staticfiles
      - media_tailwind_v:/app_local/mediafiles
    ports:
      - "8005:8005"
    expose:
      - "8005"
    extra_hosts:
      - "redis:127.0.0.1"
      - "rabbitmq:127.0.0.1"
    networks:
      - web_network
      # - main-app-external-network
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"
  traefik:
    restart: always
    depends_on:
      - frontend
    volumes:
      - static_tailwind_v:/app_local/staticfiles
      - media_tailwind_v:/app_local/mediafiles
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    build:
      context: ./docker/local/traefik
      dockerfile: Dockerfile
    container_name: django_tailwind_traefik
    image: django_tailwind_traefik_tracker:latest
    ports:
      - "8059:80"
      - "8081:8080"
    networks:
      - web_network

networks:
  # main-app-external-network:
  #   external: true
  web_network:
    driver: bridge
    
volumes:
  static_tailwind_v:
  media_tailwind_v: