version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    image: mwanjau/mlbfrontend:latest
    container_name: mlbfrontend
    # depends_on:
    #   - rabbitmq
    env_file:
      - ./.envs/.local/.django
    volumes:
      - .:/app_local
      - static_mlb_v:/app_local/staticfiles
      - media_mlb_v:/app_local/mediafiles
    # ports:
    #   - "8000:8000"
    depends_on:
      - tailwind
    expose:
      - "8000"
    # hostname: tracker_frontend
    # extra_hosts:
    #   - "redis:127.0.0.1"
    #   - "rabbitmq:127.0.0.1"
      # - "postgres:127.0.0.1"
    networks:
      - proxy
    # labels: # new
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.django.rule=Host(`tracker.local`)"
  
  tailwind:
    build:
      context: .
      dockerfile: ./docker/local/tailwind/Dockerfile
    command: /start_tailwind
    image: mwanjau/mlbtailwind:latest
    # image: 291567501831.dkr.ecr.eu-west-1.amazonaws.com/testracker_tailwind_tracker:latest
    container_name: mlbtailwind
    # depends_on:
    #   - frontend
    env_file:
      - ./.envs/.local/.django
    volumes:
      - .:/app_local
      - static_mlb_v:/app_local/staticfiles
      - media_mlb_v:/app_local/mediafiles
    networks:
      - proxy
    tty: true
  
  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-flower
  #   image: ocr2.devocp.safaricom.net/beaver-squad/flower_tracker:latest
  #   # image: 291567501831.dkr.ecr.eu-west-1.amazonaws.com/testracker_flower_tracker:latest
  #   container_name: flower_tracker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.envs/.local/.django
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - frontend
  #     - celery_worker
  #   networks:
  #     - proxy

  # redis:
  #   image: redis:7-alpine
  #   networks:
  #     - proxy

  # celery_worker:
  #   user: nobody
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-celeryworker
  #   image: ocr2.devocp.safaricom.net/beaver-squad/celery_worker_tracker:latest
  #   # image: 291567501831.dkr.ecr.eu-west-1.amazonaws.com/testracker_celery_worker_tracker:latest
  #   container_name: celery_worker_tracker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.envs/.local/.django
  #   depends_on:
  #     - frontend
  #   networks:
  #     - proxy

networks:
  proxy:
    external: true
    
volumes:
  static_mlb_v:
  media_mlb_v: