#!/bin/bash

set -o errexit
set -o nounset

# watchmedo auto-restart -d main_app/ -p '*.py' -- celery -A main_app worker --loglevel=info
# exec celery -A main_app worker -l INFO
exec celery -A main_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler