# traefik.dev.toml

# listen on port 80
[entryPoints]
  [entryPoints.web]
    address = ":82"

[experimental.plugins.geoblock]
  moduleName = "github.com/PascalMinder/geoblock"
  version = "v0.2.5"
# Traefik dashboard over http
[api]
insecure = true
dashboard = true

[log]
level = "DEBUG"

[accessLog]

# containers are not discovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false