# Generated by Django 4.2.1 on 2023-05-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='about me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=20, verbose_name='gender')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('analyst', 'analyst'), ('Project Manager', 'Project Manager'), ('Partner', 'Partner')], default='Project Manager', max_length=20, verbose_name='role')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='profile photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            managers=[
                ('pms', django.db.models.manager.Manager()),
            ],
        ),
    ]
