# traefik.prod.toml


# listen on port 80
# [entryPoints]
#   [entryPoints.web]
#     address = ":80"
# Traefik dashboard over http
debug = true
defaultEntryPoints = ["https", "http"]

# [web]
#   address = ":8090"

[log]
level = "DEBUG"

[accessLog]


[entryPoints]
  [entryPoints.dashboard]
    address = ":8090"
  [entryPoints.web]
    address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
  [entryPoints.websecure]
    address = ":443"
# [entryPoints]
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]
#       [[entryPoints.https.tls.certificates]]
#       certFile = "/app_local/ssl/cert.crt"
#       keyFile = "/app_local/ssl/cert.key"
# containers are not discovered automatically


[api]
# entrypoint="dashboard"
# insecure = true
dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false


# [entryPoints]
#   [entryPoints.web]
#     address = ":80"
#   [entryPoints.web.http]
#     [entryPoints.web.http.redirections]
#       [entryPoints.web.http.redirections.entryPoint]
#         to = "websecure"
#         scheme = "https"

#   [entryPoints.websecure]
#     address = ":443"

# [accessLog]


# [web]
#   address = ":80"
  
# [api]
#   dashboard = true
#   address = ":8090"

# [providers]
#   [providers.docker]
#     exposedByDefault = false

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/app_production/ssl/cert.crt"
      keyFile  = "/app_production/ssl/cert.key"

[certificatesResolvers.letsencrypt.acme]
  email = "maina.wanjau@gmail.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"