#!/bin/bash

set -o errexit
set -o nounset

# watchmedo auto-restart -d tracker_app/ -p '*.py' -- celery -A tracker_app worker --loglevel=info
# exec celery -A tracker_app worker -l INFO
exec celery -A tracker_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler